# Generated by Django 6.0.5 on 2026-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_userprofile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("ru", "Русский"), ("en", "English"), ("kk", "Қазақша")],
                default="ru",
                max_length=10,
            ),
        ),
    ]
