# Generated by Django 6.0.5 on 2026-05-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pro_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Free"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                    ("diamond", "Diamond"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
