# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_userprofile_ai_assist_and_pro_tier_pro_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="puzzle_ai_explain_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="puzzle_ai_explain_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
