# Generated by Django 5.2.11 on 2026-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_name",
                    models.CharField(
                        default="Аноним", max_length=50, verbose_name="Имя игрока"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Новичок"),
                            ("intermediate", "Любитель"),
                            ("expert", "Эксперт"),
                            ("custom", "Свой"),
                        ],
                        max_length=20,
                        verbose_name="Сложность",
                    ),
                ),
                ("rows", models.PositiveIntegerField(verbose_name="Строки")),
                ("cols", models.PositiveIntegerField(verbose_name="Столбцы")),
                ("mines", models.PositiveIntegerField(verbose_name="Мины")),
                (
                    "result",
                    models.CharField(
                        choices=[("win", "Победа"), ("loss", "Поражение")],
                        max_length=4,
                        verbose_name="Результат",
                    ),
                ),
                ("time_seconds", models.FloatField(verbose_name="Время (сек)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Результат игры",
                "verbose_name_plural": "Результаты игр",
                "ordering": ["time_seconds"],
            },
        ),
    ]
