# Generated by Django 6.0.5 on 2026-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_gameresult_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameresult",
            name="mode",
            field=models.CharField(
                choices=[
                    ("classic", "Классический"),
                    ("speed", "Скоростной режим"),
                    ("noflag", "Без флагов"),
                    ("daily", "Ежедневный вызов"),
                    ("blind", "Вслепую"),
                    ("infinite", "Бесконечный"),
                ],
                default="classic",
                max_length=20,
                verbose_name="Режим",
            ),
        ),
    ]
